### ISSUE TITLE
Verb Issues- Find examples of when verbs can get confusing

### ISSUE THREAD

**Issue by Thomas-Romanoff** [ombegov/project-cruft#103]

**Comment by Thomas-Romanoff** [comment]
[VerbConflictExamples.xlsx](https://github.com/ombegov/project-cruft/files/758717/VerbConflictExamples.xlsx)

**Comment by Thomas-Romanoff** [comment]
@mattbailey0 The verb conflicts you asked me to look up.

**Comment by mattbailey0** [comment]
Thanks @Thomas-Romanoff!
